### PR TITLE
Feature/allow recursing directories

### PR DESCRIPTION
**Pull request by goosemo**

### CODE REVIEW

**Comment by subsetpark** [comment]
Looks  great. Will you run it through a quick `autopep8` and we can merge?

**Comment by goosemo** [comment]
Ran it over the two files changed. Seems to have made changes over more than just what I threw down. It might be nice for this to be documented in the README somewhere, or is it on a wiki page I neglected to read?

**Comment by subsetpark** [comment]
No @goosemo , we could definitely stand to mention it in the very thin contributing guidelines. Thanks!

**Comment by goosemo** [comment]
Is there anything more you'd like done @subsetpark to get this merged?

**Comment by subsetpark** [comment]
No, thanks for the reminder!

**Pull request merged**
